name: CI

#controls when the action will run
on: 
  #Triggers the workflow on push or pull request events but only for develop branch
  push: 
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called 'build'
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks they will be executed as part of the job
    steps:
      # Check-out you repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out the code
        uses: actions/checkout@v4

      # make gradlew executables first
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Runs a single command using the runners shell
      - name: Run Lint
        run: ./gradlew lintDebug

      # Runs a set of commands using the runners shell
      - name: Upload html test report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report.html
          path: app/build/reports/lint-results-debug.html

# job For Unit test cases
  unit-test:
    # Added dependency of lint, once lint gets completed then only unit-test task will get run
      needs: [ lint ]
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks they will be executed as part of the job
      steps:
        # Check-out you repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Check-out the code
          uses: actions/checkout@v4

        # make gradlew executables first
        - name: Make gradlew executable
          run: chmod +x ./gradlew

        # Runs a single command using the runners shell
        - name: Run Unit test cases
          run: ./gradlew test

        # Runs a set of commands using the runners shell
        - name: Upload html test report
          uses: actions/upload-artifact@v4
          with:
            name: test-report.html
            path: app/build/reports/tests/testDebugUnitTest/
  
